language: node_js
node_js:
  - node
branches:
  only:
    - master
cache: npm
before_install:
  - npm update
install:
  - npm install
script:
  - npm test -- -u
  - npm run coveralls -- -u
